{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simplyhelm.serviceAccountName" . }}
  labels:
{{ include "simplyhelm.labels" . | nindent 4 }}
{{- end -}}
